// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Xenorchestra
{
    public static class GetXoaPif
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Xenorchestra = Pulumi.Xenorchestra;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var eth0 = Xenorchestra.GetXoaPif.Invoke(new()
        ///     {
        ///         Device = "eth0",
        ///         Vlan = -1,
        ///     });
        /// 
        ///     var demo_vm = new Xenorchestra.Vm("demo-vm", new()
        ///     {
        ///         Networks = new[]
        ///         {
        ///             new Xenorchestra.Inputs.VmNetworkArgs
        ///             {
        ///                 NetworkId = eth0.Apply(getXoaPifResult =&gt; getXoaPifResult.Network),
        ///             },
        ///         },
        ///     });
        /// 
        ///     // ...
        /// });
        /// ```
        /// </summary>
        public static Task<GetXoaPifResult> InvokeAsync(GetXoaPifArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetXoaPifResult>("xenorchestra:index/getXoaPif:getXoaPif", args ?? new GetXoaPifArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Xenorchestra = Pulumi.Xenorchestra;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var eth0 = Xenorchestra.GetXoaPif.Invoke(new()
        ///     {
        ///         Device = "eth0",
        ///         Vlan = -1,
        ///     });
        /// 
        ///     var demo_vm = new Xenorchestra.Vm("demo-vm", new()
        ///     {
        ///         Networks = new[]
        ///         {
        ///             new Xenorchestra.Inputs.VmNetworkArgs
        ///             {
        ///                 NetworkId = eth0.Apply(getXoaPifResult =&gt; getXoaPifResult.Network),
        ///             },
        ///         },
        ///     });
        /// 
        ///     // ...
        /// });
        /// ```
        /// </summary>
        public static Output<GetXoaPifResult> Invoke(GetXoaPifInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetXoaPifResult>("xenorchestra:index/getXoaPif:getXoaPif", args ?? new GetXoaPifInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Xenorchestra = Pulumi.Xenorchestra;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var eth0 = Xenorchestra.GetXoaPif.Invoke(new()
        ///     {
        ///         Device = "eth0",
        ///         Vlan = -1,
        ///     });
        /// 
        ///     var demo_vm = new Xenorchestra.Vm("demo-vm", new()
        ///     {
        ///         Networks = new[]
        ///         {
        ///             new Xenorchestra.Inputs.VmNetworkArgs
        ///             {
        ///                 NetworkId = eth0.Apply(getXoaPifResult =&gt; getXoaPifResult.Network),
        ///             },
        ///         },
        ///     });
        /// 
        ///     // ...
        /// });
        /// ```
        /// </summary>
        public static Output<GetXoaPifResult> Invoke(GetXoaPifInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetXoaPifResult>("xenorchestra:index/getXoaPif:getXoaPif", args ?? new GetXoaPifInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetXoaPifArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the network device. Examples include eth0, eth1, etc. See `Ifconfig` for possible devices.
        /// </summary>
        [Input("device", required: true)]
        public string Device { get; set; } = null!;

        /// <summary>
        /// The ID of the host that the PIF belongs to.
        /// </summary>
        [Input("hostId")]
        public string? HostId { get; set; }

        /// <summary>
        /// The VLAN the PIF belongs to.
        /// </summary>
        [Input("vlan", required: true)]
        public int Vlan { get; set; }

        public GetXoaPifArgs()
        {
        }
        public static new GetXoaPifArgs Empty => new GetXoaPifArgs();
    }

    public sealed class GetXoaPifInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the network device. Examples include eth0, eth1, etc. See `Ifconfig` for possible devices.
        /// </summary>
        [Input("device", required: true)]
        public Input<string> Device { get; set; } = null!;

        /// <summary>
        /// The ID of the host that the PIF belongs to.
        /// </summary>
        [Input("hostId")]
        public Input<string>? HostId { get; set; }

        /// <summary>
        /// The VLAN the PIF belongs to.
        /// </summary>
        [Input("vlan", required: true)]
        public Input<int> Vlan { get; set; } = null!;

        public GetXoaPifInvokeArgs()
        {
        }
        public static new GetXoaPifInvokeArgs Empty => new GetXoaPifInvokeArgs();
    }


    [OutputType]
    public sealed class GetXoaPifResult
    {
        /// <summary>
        /// If the PIF is attached to the network.
        /// </summary>
        public readonly bool Attached;
        /// <summary>
        /// In case of a bond slave, the uuid of the bond master.
        /// </summary>
        public readonly string BondMaster;
        /// <summary>
        /// In case of a bond master, the PIFs (uuid) that are used for this bond.
        /// </summary>
        public readonly ImmutableArray<string> BondSlaves;
        /// <summary>
        /// The name of the network device. Examples include eth0, eth1, etc. See `Ifconfig` for possible devices.
        /// </summary>
        public readonly string Device;
        /// <summary>
        /// The host the PIF is associated with.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// The ID of the host that the PIF belongs to.
        /// </summary>
        public readonly string HostId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// True if this PIF is a bond master.
        /// </summary>
        public readonly bool IsBondMaster;
        /// <summary>
        /// True if this PIF is a bond slave.
        /// </summary>
        public readonly bool IsBondSlave;
        /// <summary>
        /// The network the PIF is associated with.
        /// </summary>
        public readonly string Network;
        /// <summary>
        /// The pool the PIF is associated with.
        /// </summary>
        public readonly string PoolId;
        /// <summary>
        /// The uuid of the PIF.
        /// </summary>
        public readonly string Uuid;
        /// <summary>
        /// The VLAN the PIF belongs to.
        /// </summary>
        public readonly int Vlan;

        [OutputConstructor]
        private GetXoaPifResult(
            bool attached,

            string bondMaster,

            ImmutableArray<string> bondSlaves,

            string device,

            string host,

            string hostId,

            string id,

            bool isBondMaster,

            bool isBondSlave,

            string network,

            string poolId,

            string uuid,

            int vlan)
        {
            Attached = attached;
            BondMaster = bondMaster;
            BondSlaves = bondSlaves;
            Device = device;
            Host = host;
            HostId = hostId;
            Id = id;
            IsBondMaster = isBondMaster;
            IsBondSlave = isBondSlave;
            Network = network;
            PoolId = poolId;
            Uuid = uuid;
            Vlan = vlan;
        }
    }
}
