# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetXoaVdiResult',
    'AwaitableGetXoaVdiResult',
    'get_xoa_vdi',
    'get_xoa_vdi_output',
]

@pulumi.output_type
class GetXoaVdiResult:
    """
    A collection of values returned by getXoaVdi.
    """
    def __init__(__self__, id=None, name_label=None, parent=None, pool_id=None, tags=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name_label and not isinstance(name_label, str):
            raise TypeError("Expected argument 'name_label' to be a str")
        pulumi.set(__self__, "name_label", name_label)
        if parent and not isinstance(parent, str):
            raise TypeError("Expected argument 'parent' to be a str")
        pulumi.set(__self__, "parent", parent)
        if pool_id and not isinstance(pool_id, str):
            raise TypeError("Expected argument 'pool_id' to be a str")
        pulumi.set(__self__, "pool_id", pool_id)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The ID of the VDI.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="nameLabel")
    def name_label(self) -> Optional[_builtins.str]:
        """
        The name of the VDI to look up.
        """
        return pulumi.get(self, "name_label")

    @_builtins.property
    @pulumi.getter
    def parent(self) -> _builtins.str:
        """
        The ID of the parent VDI if one exists. An example of when a VDI will have a parent is when it was created from a VM fast clone.
        """
        return pulumi.get(self, "parent")

    @_builtins.property
    @pulumi.getter(name="poolId")
    def pool_id(self) -> Optional[_builtins.str]:
        """
        The ID of the pool the VDI belongs to. This is useful if you have a VDI with the same name on different pools.
        """
        return pulumi.get(self, "pool_id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Sequence[_builtins.str]]:
        """
        The tags (labels) applied to the given entity. Not used for filtering if empty.
        """
        return pulumi.get(self, "tags")


class AwaitableGetXoaVdiResult(GetXoaVdiResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetXoaVdiResult(
            id=self.id,
            name_label=self.name_label,
            parent=self.parent,
            pool_id=self.pool_id,
            tags=self.tags)


def get_xoa_vdi(id: Optional[_builtins.str] = None,
                name_label: Optional[_builtins.str] = None,
                pool_id: Optional[_builtins.str] = None,
                tags: Optional[Sequence[_builtins.str]] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetXoaVdiResult:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_xenorchestra as xenorchestra

    vdi = xenorchestra.get_xoa_vdi(name_label="ubuntu-20.04.4-live-server-amd64.iso")
    demo_vm = xenorchestra.Vm("demo-vm", cdrom=vdi.id[0])
    ```


    :param _builtins.str id: The ID of the VDI.
    :param _builtins.str name_label: The name of the VDI to look up.
    :param _builtins.str pool_id: The ID of the pool the VDI belongs to. This is useful if you have a VDI with the same name on different pools.
    :param Sequence[_builtins.str] tags: The tags (labels) applied to the given entity. Not used for filtering if empty.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['nameLabel'] = name_label
    __args__['poolId'] = pool_id
    __args__['tags'] = tags
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('xenorchestra:index/getXoaVdi:getXoaVdi', __args__, opts=opts, typ=GetXoaVdiResult).value

    return AwaitableGetXoaVdiResult(
        id=pulumi.get(__ret__, 'id'),
        name_label=pulumi.get(__ret__, 'name_label'),
        parent=pulumi.get(__ret__, 'parent'),
        pool_id=pulumi.get(__ret__, 'pool_id'),
        tags=pulumi.get(__ret__, 'tags'))
def get_xoa_vdi_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                       name_label: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                       pool_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                       tags: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetXoaVdiResult]:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_xenorchestra as xenorchestra

    vdi = xenorchestra.get_xoa_vdi(name_label="ubuntu-20.04.4-live-server-amd64.iso")
    demo_vm = xenorchestra.Vm("demo-vm", cdrom=vdi.id[0])
    ```


    :param _builtins.str id: The ID of the VDI.
    :param _builtins.str name_label: The name of the VDI to look up.
    :param _builtins.str pool_id: The ID of the pool the VDI belongs to. This is useful if you have a VDI with the same name on different pools.
    :param Sequence[_builtins.str] tags: The tags (labels) applied to the given entity. Not used for filtering if empty.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['nameLabel'] = name_label
    __args__['poolId'] = pool_id
    __args__['tags'] = tags
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('xenorchestra:index/getXoaVdi:getXoaVdi', __args__, opts=opts, typ=GetXoaVdiResult)
    return __ret__.apply(lambda __response__: GetXoaVdiResult(
        id=pulumi.get(__response__, 'id'),
        name_label=pulumi.get(__response__, 'name_label'),
        parent=pulumi.get(__response__, 'parent'),
        pool_id=pulumi.get(__response__, 'pool_id'),
        tags=pulumi.get(__response__, 'tags')))
