# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetXoaPoolsResult',
    'AwaitableGetXoaPoolsResult',
    'get_xoa_pools',
    'get_xoa_pools_output',
]

@pulumi.output_type
class GetXoaPoolsResult:
    """
    A collection of values returned by getXoaPools.
    """
    def __init__(__self__, id=None, pools=None, sort_by=None, sort_order=None, tags=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if pools and not isinstance(pools, list):
            raise TypeError("Expected argument 'pools' to be a list")
        pulumi.set(__self__, "pools", pools)
        if sort_by and not isinstance(sort_by, str):
            raise TypeError("Expected argument 'sort_by' to be a str")
        pulumi.set(__self__, "sort_by", sort_by)
        if sort_order and not isinstance(sort_order, str):
            raise TypeError("Expected argument 'sort_order' to be a str")
        pulumi.set(__self__, "sort_order", sort_order)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def pools(self) -> Sequence['outputs.GetXoaPoolsPoolResult']:
        """
        The resulting pools after applying the argument filtering.
        """
        return pulumi.get(self, "pools")

    @_builtins.property
    @pulumi.getter(name="sortBy")
    def sort_by(self) -> Optional[_builtins.str]:
        """
        The pool field to sort the results by (id and name_label are supported).
        """
        return pulumi.get(self, "sort_by")

    @_builtins.property
    @pulumi.getter(name="sortOrder")
    def sort_order(self) -> Optional[_builtins.str]:
        """
        Valid options are `asc` or `desc` and sort order is applied to `sort_by` argument.
        """
        return pulumi.get(self, "sort_order")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Sequence[_builtins.str]]:
        """
        The tags (labels) applied to the given entity. Not used for filtering if empty.
        """
        return pulumi.get(self, "tags")


class AwaitableGetXoaPoolsResult(GetXoaPoolsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetXoaPoolsResult(
            id=self.id,
            pools=self.pools,
            sort_by=self.sort_by,
            sort_order=self.sort_order,
            tags=self.tags)


def get_xoa_pools(sort_by: Optional[_builtins.str] = None,
                  sort_order: Optional[_builtins.str] = None,
                  tags: Optional[Sequence[_builtins.str]] = None,
                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetXoaPoolsResult:
    """
    Use this data source to filter Xenorchestra pools by certain criteria (tags) for use in other resources.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_xenorchestra as xenorchestra

    all = xenorchestra.get_xoa_pools()
    tagged = xenorchestra.get_xoa_pools(tags=[
        "production",
        "web",
    ])
    sorted = xenorchestra.get_xoa_pools(sort_by="name_label",
        sort_order="asc")
    example = xenorchestra.get_xoa_pools(tags=["terraform-managed"])
    local_storage = xenorchestra.get_xoa_storage_repository(name_label="Local storage",
        pool_id=example.pools[0].id)
    ```


    :param _builtins.str sort_by: The pool field to sort the results by (id and name_label are supported).
    :param _builtins.str sort_order: Valid options are `asc` or `desc` and sort order is applied to `sort_by` argument.
    :param Sequence[_builtins.str] tags: The tags (labels) applied to the given entity. Not used for filtering if empty.
    """
    __args__ = dict()
    __args__['sortBy'] = sort_by
    __args__['sortOrder'] = sort_order
    __args__['tags'] = tags
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('xenorchestra:index/getXoaPools:getXoaPools', __args__, opts=opts, typ=GetXoaPoolsResult).value

    return AwaitableGetXoaPoolsResult(
        id=pulumi.get(__ret__, 'id'),
        pools=pulumi.get(__ret__, 'pools'),
        sort_by=pulumi.get(__ret__, 'sort_by'),
        sort_order=pulumi.get(__ret__, 'sort_order'),
        tags=pulumi.get(__ret__, 'tags'))
def get_xoa_pools_output(sort_by: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                         sort_order: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                         tags: pulumi.Input[Optional[Optional[Sequence[_builtins.str]]]] = None,
                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetXoaPoolsResult]:
    """
    Use this data source to filter Xenorchestra pools by certain criteria (tags) for use in other resources.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_xenorchestra as xenorchestra

    all = xenorchestra.get_xoa_pools()
    tagged = xenorchestra.get_xoa_pools(tags=[
        "production",
        "web",
    ])
    sorted = xenorchestra.get_xoa_pools(sort_by="name_label",
        sort_order="asc")
    example = xenorchestra.get_xoa_pools(tags=["terraform-managed"])
    local_storage = xenorchestra.get_xoa_storage_repository(name_label="Local storage",
        pool_id=example.pools[0].id)
    ```


    :param _builtins.str sort_by: The pool field to sort the results by (id and name_label are supported).
    :param _builtins.str sort_order: Valid options are `asc` or `desc` and sort order is applied to `sort_by` argument.
    :param Sequence[_builtins.str] tags: The tags (labels) applied to the given entity. Not used for filtering if empty.
    """
    __args__ = dict()
    __args__['sortBy'] = sort_by
    __args__['sortOrder'] = sort_order
    __args__['tags'] = tags
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('xenorchestra:index/getXoaPools:getXoaPools', __args__, opts=opts, typ=GetXoaPoolsResult)
    return __ret__.apply(lambda __response__: GetXoaPoolsResult(
        id=pulumi.get(__response__, 'id'),
        pools=pulumi.get(__response__, 'pools'),
        sort_by=pulumi.get(__response__, 'sort_by'),
        sort_order=pulumi.get(__response__, 'sort_order'),
        tags=pulumi.get(__response__, 'tags')))
