// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Xenorchestra.Outputs
{

    [OutputType]
    public sealed class GetVmsVmNetworkResult
    {
        /// <summary>
        /// Whether the device should be attached to the VM.
        /// </summary>
        public readonly bool? Attached;
        public readonly string Device;
        public readonly string? ExpectedIpCidr;
        public readonly ImmutableArray<string> Ipv4Addresses;
        public readonly ImmutableArray<string> Ipv6Addresses;
        public readonly string MacAddress;
        /// <summary>
        /// The ID of the network the VM will be on.
        /// </summary>
        public readonly string NetworkId;

        [OutputConstructor]
        private GetVmsVmNetworkResult(
            bool? attached,

            string device,

            string? expectedIpCidr,

            ImmutableArray<string> ipv4Addresses,

            ImmutableArray<string> ipv6Addresses,

            string macAddress,

            string networkId)
        {
            Attached = attached;
            Device = device;
            ExpectedIpCidr = expectedIpCidr;
            Ipv4Addresses = ipv4Addresses;
            Ipv6Addresses = ipv6Addresses;
            MacAddress = macAddress;
            NetworkId = networkId;
        }
    }
}
