// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to filter Xenorchestra pools by certain criteria (tags) for use in other resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as xenorchestra from "@vates/pulumi-xenorchestra";
 *
 * const all = xenorchestra.getXoaPools({});
 * const tagged = xenorchestra.getXoaPools({
 *     tags: [
 *         "production",
 *         "web",
 *     ],
 * });
 * const sorted = xenorchestra.getXoaPools({
 *     sortBy: "name_label",
 *     sortOrder: "asc",
 * });
 * const example = xenorchestra.getXoaPools({
 *     tags: ["terraform-managed"],
 * });
 * const localStorage = example.then(example => xenorchestra.getXoaStorageRepository({
 *     nameLabel: "Local storage",
 *     poolId: example.pools?.[0]?.id,
 * }));
 * ```
 */
export function getXoaPools(args?: GetXoaPoolsArgs, opts?: pulumi.InvokeOptions): Promise<GetXoaPoolsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("xenorchestra:index/getXoaPools:getXoaPools", {
        "sortBy": args.sortBy,
        "sortOrder": args.sortOrder,
        "tags": args.tags,
    }, opts);
}

/**
 * A collection of arguments for invoking getXoaPools.
 */
export interface GetXoaPoolsArgs {
    /**
     * The pool field to sort the results by (id and nameLabel are supported).
     */
    sortBy?: string;
    /**
     * Valid options are `asc` or `desc` and sort order is applied to `sortBy` argument.
     */
    sortOrder?: string;
    /**
     * The tags (labels) applied to the given entity. Not used for filtering if empty.
     */
    tags?: string[];
}

/**
 * A collection of values returned by getXoaPools.
 */
export interface GetXoaPoolsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The resulting pools after applying the argument filtering.
     */
    readonly pools: outputs.GetXoaPoolsPool[];
    /**
     * The pool field to sort the results by (id and nameLabel are supported).
     */
    readonly sortBy?: string;
    /**
     * Valid options are `asc` or `desc` and sort order is applied to `sortBy` argument.
     */
    readonly sortOrder?: string;
    /**
     * The tags (labels) applied to the given entity. Not used for filtering if empty.
     */
    readonly tags?: string[];
}
/**
 * Use this data source to filter Xenorchestra pools by certain criteria (tags) for use in other resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as xenorchestra from "@vates/pulumi-xenorchestra";
 *
 * const all = xenorchestra.getXoaPools({});
 * const tagged = xenorchestra.getXoaPools({
 *     tags: [
 *         "production",
 *         "web",
 *     ],
 * });
 * const sorted = xenorchestra.getXoaPools({
 *     sortBy: "name_label",
 *     sortOrder: "asc",
 * });
 * const example = xenorchestra.getXoaPools({
 *     tags: ["terraform-managed"],
 * });
 * const localStorage = example.then(example => xenorchestra.getXoaStorageRepository({
 *     nameLabel: "Local storage",
 *     poolId: example.pools?.[0]?.id,
 * }));
 * ```
 */
export function getXoaPoolsOutput(args?: GetXoaPoolsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetXoaPoolsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("xenorchestra:index/getXoaPools:getXoaPools", {
        "sortBy": args.sortBy,
        "sortOrder": args.sortOrder,
        "tags": args.tags,
    }, opts);
}

/**
 * A collection of arguments for invoking getXoaPools.
 */
export interface GetXoaPoolsOutputArgs {
    /**
     * The pool field to sort the results by (id and nameLabel are supported).
     */
    sortBy?: pulumi.Input<string | undefined>;
    /**
     * Valid options are `asc` or `desc` and sort order is applied to `sortBy` argument.
     */
    sortOrder?: pulumi.Input<string | undefined>;
    /**
     * The tags (labels) applied to the given entity. Not used for filtering if empty.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
