// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 */
export class Vm extends pulumi.CustomResource {
    /**
     * Get an existing Vm resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VmState, opts?: pulumi.CustomResourceOptions): Vm {
        return new Vm(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'xenorchestra:index/vm:Vm';

    /**
     * Returns true if the given object is an instance of Vm.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Vm {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Vm.__pulumiType;
    }

    /**
     * The preferred host you would like the VM to run on. If changed on an existing VM it will require a reboot for the VM to be rescheduled.
     */
    declare public readonly affinityHost: pulumi.Output<string | undefined>;
    /**
     * If the VM will automatically turn on. Defaults to `false`.
     */
    declare public readonly autoPoweron: pulumi.Output<boolean | undefined>;
    /**
     * List of operations on a VM that are not permitted. Examples include: clean_reboot, clean_shutdown, hard_reboot, hard_shutdown, pause, shutdown, suspend, destroy. See: https://xapi-project.github.io/xen-api/classes/vm.html#enum_vm_operations
     */
    declare public readonly blockedOperations: pulumi.Output<string[] | undefined>;
    /**
     * The ISO that should be attached to VM. This allows you to create a VM from a diskless template (any templates available from `xe template-list`) and install the OS from the following ISO.
     */
    declare public readonly cdrom: pulumi.Output<outputs.VmCdrom | undefined>;
    /**
     * The type of clone to perform for the VM. Possible values include `fast` or `full` and defaults to `fast`. In order to perform a `full` clone, the VM template must not be a disk template.
     */
    declare public readonly cloneType: pulumi.Output<string | undefined>;
    /**
     * The content of the cloud-init config to use. See the cloud init docs for more [information](https://cloudinit.readthedocs.io/en/latest/topics/examples.html).
     */
    declare public readonly cloudConfig: pulumi.Output<string | undefined>;
    /**
     * The content of the cloud-init network configuration for the VM (uses [version 1](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html))
     */
    declare public readonly cloudNetworkConfig: pulumi.Output<string | undefined>;
    declare public readonly coreOs: pulumi.Output<boolean | undefined>;
    declare public readonly cpuCap: pulumi.Output<number | undefined>;
    declare public readonly cpuWeight: pulumi.Output<number | undefined>;
    /**
     * The number of CPUs the VM will have. Updates to this field will cause a stop and start of the VM if the new CPU value is greater than the max CPU value. This can be determined with the following command:
     * ```
     *
     * $ xo-cli xo.getAllObjects filter='json:{"id": "cf7b5d7d-3cd5-6b7c-5025-5c935c8cd0b8"}' | jq '.[].CPUs'
     * {
     *   "max": 4,
     *   "number": 2
     * }
     *
     * # Updating the VM to use 3 CPUs would happen without stopping/starting the VM
     * # Updating the VM to use 5 CPUs would stop/start the VM
     * ```
     */
    declare public readonly cpus: pulumi.Output<number>;
    /**
     * Determines whether the cloud config VDI should be deleted once the VM has booted. Defaults to `false`. If set to `true`, powerState must be set to `Running`.
     */
    declare public readonly destroyCloudConfigVdiAfterBoot: pulumi.Output<boolean | undefined>;
    /**
     * The disk the VM will have access to.
     */
    declare public readonly disks: pulumi.Output<outputs.VmDisk[]>;
    /**
     * Boolean parameter that allows a VM to use nested virtualization.
     */
    declare public readonly expNestedHvm: pulumi.Output<boolean | undefined>;
    /**
     * The restart priority for the VM. Possible values are `best-effort`, `restart` and empty string (no restarts on failure. Defaults to empty string
     */
    declare public readonly highAvailability: pulumi.Output<string | undefined>;
    declare public readonly host: pulumi.Output<string | undefined>;
    /**
     * The firmware to use for the VM. Possible values are `bios` and `uefi`.
     */
    declare public readonly hvmBootFirmware: pulumi.Output<string | undefined>;
    /**
     * This cannot be used with `cdrom`. Possible values are `network` which allows a VM to boot via PXE.
     */
    declare public readonly installationMethod: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly ipv4Addresses: pulumi.Output<string[]>;
    /**
     * This is only accessible if guest-tools is installed in the VM. While the output contains a list of ipv6 addresses, the presence of an IP address is only guaranteed if `expectedIpCidr` is set for that interface. The list contains the ipv6 addresses across all network interfaces in order.
     */
    declare public /*out*/ readonly ipv6Addresses: pulumi.Output<string[]>;
    /**
     * The amount of memory in bytes the VM will have.\n\n!!! WARNING: Updates to this field will cause the VM to stop and start, as it sets both dynamic and static maximums.
     */
    declare public readonly memoryMax: pulumi.Output<number>;
    /**
     * The amount of memory in bytes the VM will have. Set this value equal to memoryMax to have a static memory.
     */
    declare public readonly memoryMin: pulumi.Output<number>;
    /**
     * The description of the VM.
     */
    declare public readonly nameDescription: pulumi.Output<string | undefined>;
    /**
     * The name of the VM.
     */
    declare public readonly nameLabel: pulumi.Output<string>;
    /**
     * The network for the VM.
     */
    declare public readonly networks: pulumi.Output<outputs.VmNetwork[]>;
    /**
     * The power state of the VM. This can be Running, Halted, Paused or Suspended.
     */
    declare public readonly powerState: pulumi.Output<string | undefined>;
    declare public readonly resourceSet: pulumi.Output<string | undefined>;
    /**
     * Enable UEFI secure boot for the VM.
     */
    declare public readonly secureBoot: pulumi.Output<boolean | undefined>;
    /**
     * Number of seconds the VM should be delayed from starting.
     */
    declare public readonly startDelay: pulumi.Output<number | undefined>;
    /**
     * The tags (labels) applied to the given entity. Not used for filtering if empty.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * The ID of the VM template to create the new VM from.
     */
    declare public readonly template: pulumi.Output<string>;
    /**
     * The video adapter the VM should use. Possible values include std and cirrus.
     */
    declare public readonly vga: pulumi.Output<string | undefined>;
    /**
     * The videoram option the VM should use. Possible values include 1, 2, 4, 8, 16
     */
    declare public readonly videoram: pulumi.Output<number | undefined>;
    /**
     * The key value pairs to be populated in xenstore.
     */
    declare public readonly xenstore: pulumi.Output<{[key: string]: string} | undefined>;

    /**
     * Create a Vm resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VmArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VmArgs | VmState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VmState | undefined;
            resourceInputs["affinityHost"] = state?.affinityHost;
            resourceInputs["autoPoweron"] = state?.autoPoweron;
            resourceInputs["blockedOperations"] = state?.blockedOperations;
            resourceInputs["cdrom"] = state?.cdrom;
            resourceInputs["cloneType"] = state?.cloneType;
            resourceInputs["cloudConfig"] = state?.cloudConfig;
            resourceInputs["cloudNetworkConfig"] = state?.cloudNetworkConfig;
            resourceInputs["coreOs"] = state?.coreOs;
            resourceInputs["cpuCap"] = state?.cpuCap;
            resourceInputs["cpuWeight"] = state?.cpuWeight;
            resourceInputs["cpus"] = state?.cpus;
            resourceInputs["destroyCloudConfigVdiAfterBoot"] = state?.destroyCloudConfigVdiAfterBoot;
            resourceInputs["disks"] = state?.disks;
            resourceInputs["expNestedHvm"] = state?.expNestedHvm;
            resourceInputs["highAvailability"] = state?.highAvailability;
            resourceInputs["host"] = state?.host;
            resourceInputs["hvmBootFirmware"] = state?.hvmBootFirmware;
            resourceInputs["installationMethod"] = state?.installationMethod;
            resourceInputs["ipv4Addresses"] = state?.ipv4Addresses;
            resourceInputs["ipv6Addresses"] = state?.ipv6Addresses;
            resourceInputs["memoryMax"] = state?.memoryMax;
            resourceInputs["memoryMin"] = state?.memoryMin;
            resourceInputs["nameDescription"] = state?.nameDescription;
            resourceInputs["nameLabel"] = state?.nameLabel;
            resourceInputs["networks"] = state?.networks;
            resourceInputs["powerState"] = state?.powerState;
            resourceInputs["resourceSet"] = state?.resourceSet;
            resourceInputs["secureBoot"] = state?.secureBoot;
            resourceInputs["startDelay"] = state?.startDelay;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["template"] = state?.template;
            resourceInputs["vga"] = state?.vga;
            resourceInputs["videoram"] = state?.videoram;
            resourceInputs["xenstore"] = state?.xenstore;
        } else {
            const args = argsOrState as VmArgs | undefined;
            if (args?.cpus === undefined && !opts.urn) {
                throw new Error("Missing required property 'cpus'");
            }
            if (args?.disks === undefined && !opts.urn) {
                throw new Error("Missing required property 'disks'");
            }
            if (args?.memoryMax === undefined && !opts.urn) {
                throw new Error("Missing required property 'memoryMax'");
            }
            if (args?.nameLabel === undefined && !opts.urn) {
                throw new Error("Missing required property 'nameLabel'");
            }
            if (args?.networks === undefined && !opts.urn) {
                throw new Error("Missing required property 'networks'");
            }
            if (args?.template === undefined && !opts.urn) {
                throw new Error("Missing required property 'template'");
            }
            resourceInputs["affinityHost"] = args?.affinityHost;
            resourceInputs["autoPoweron"] = args?.autoPoweron;
            resourceInputs["blockedOperations"] = args?.blockedOperations;
            resourceInputs["cdrom"] = args?.cdrom;
            resourceInputs["cloneType"] = args?.cloneType;
            resourceInputs["cloudConfig"] = args?.cloudConfig;
            resourceInputs["cloudNetworkConfig"] = args?.cloudNetworkConfig;
            resourceInputs["coreOs"] = args?.coreOs;
            resourceInputs["cpuCap"] = args?.cpuCap;
            resourceInputs["cpuWeight"] = args?.cpuWeight;
            resourceInputs["cpus"] = args?.cpus;
            resourceInputs["destroyCloudConfigVdiAfterBoot"] = args?.destroyCloudConfigVdiAfterBoot;
            resourceInputs["disks"] = args?.disks;
            resourceInputs["expNestedHvm"] = args?.expNestedHvm;
            resourceInputs["highAvailability"] = args?.highAvailability;
            resourceInputs["host"] = args?.host;
            resourceInputs["hvmBootFirmware"] = args?.hvmBootFirmware;
            resourceInputs["installationMethod"] = args?.installationMethod;
            resourceInputs["memoryMax"] = args?.memoryMax;
            resourceInputs["memoryMin"] = args?.memoryMin;
            resourceInputs["nameDescription"] = args?.nameDescription;
            resourceInputs["nameLabel"] = args?.nameLabel;
            resourceInputs["networks"] = args?.networks;
            resourceInputs["powerState"] = args?.powerState;
            resourceInputs["resourceSet"] = args?.resourceSet;
            resourceInputs["secureBoot"] = args?.secureBoot;
            resourceInputs["startDelay"] = args?.startDelay;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["template"] = args?.template;
            resourceInputs["vga"] = args?.vga;
            resourceInputs["videoram"] = args?.videoram;
            resourceInputs["xenstore"] = args?.xenstore;
            resourceInputs["ipv4Addresses"] = undefined /*out*/;
            resourceInputs["ipv6Addresses"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Vm.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Vm resources.
 */
export interface VmState {
    /**
     * The preferred host you would like the VM to run on. If changed on an existing VM it will require a reboot for the VM to be rescheduled.
     */
    affinityHost?: pulumi.Input<string>;
    /**
     * If the VM will automatically turn on. Defaults to `false`.
     */
    autoPoweron?: pulumi.Input<boolean>;
    /**
     * List of operations on a VM that are not permitted. Examples include: clean_reboot, clean_shutdown, hard_reboot, hard_shutdown, pause, shutdown, suspend, destroy. See: https://xapi-project.github.io/xen-api/classes/vm.html#enum_vm_operations
     */
    blockedOperations?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ISO that should be attached to VM. This allows you to create a VM from a diskless template (any templates available from `xe template-list`) and install the OS from the following ISO.
     */
    cdrom?: pulumi.Input<inputs.VmCdrom>;
    /**
     * The type of clone to perform for the VM. Possible values include `fast` or `full` and defaults to `fast`. In order to perform a `full` clone, the VM template must not be a disk template.
     */
    cloneType?: pulumi.Input<string>;
    /**
     * The content of the cloud-init config to use. See the cloud init docs for more [information](https://cloudinit.readthedocs.io/en/latest/topics/examples.html).
     */
    cloudConfig?: pulumi.Input<string>;
    /**
     * The content of the cloud-init network configuration for the VM (uses [version 1](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html))
     */
    cloudNetworkConfig?: pulumi.Input<string>;
    coreOs?: pulumi.Input<boolean>;
    cpuCap?: pulumi.Input<number>;
    cpuWeight?: pulumi.Input<number>;
    /**
     * The number of CPUs the VM will have. Updates to this field will cause a stop and start of the VM if the new CPU value is greater than the max CPU value. This can be determined with the following command:
     * ```
     *
     * $ xo-cli xo.getAllObjects filter='json:{"id": "cf7b5d7d-3cd5-6b7c-5025-5c935c8cd0b8"}' | jq '.[].CPUs'
     * {
     *   "max": 4,
     *   "number": 2
     * }
     *
     * # Updating the VM to use 3 CPUs would happen without stopping/starting the VM
     * # Updating the VM to use 5 CPUs would stop/start the VM
     * ```
     */
    cpus?: pulumi.Input<number>;
    /**
     * Determines whether the cloud config VDI should be deleted once the VM has booted. Defaults to `false`. If set to `true`, powerState must be set to `Running`.
     */
    destroyCloudConfigVdiAfterBoot?: pulumi.Input<boolean>;
    /**
     * The disk the VM will have access to.
     */
    disks?: pulumi.Input<pulumi.Input<inputs.VmDisk>[]>;
    /**
     * Boolean parameter that allows a VM to use nested virtualization.
     */
    expNestedHvm?: pulumi.Input<boolean>;
    /**
     * The restart priority for the VM. Possible values are `best-effort`, `restart` and empty string (no restarts on failure. Defaults to empty string
     */
    highAvailability?: pulumi.Input<string>;
    host?: pulumi.Input<string>;
    /**
     * The firmware to use for the VM. Possible values are `bios` and `uefi`.
     */
    hvmBootFirmware?: pulumi.Input<string>;
    /**
     * This cannot be used with `cdrom`. Possible values are `network` which allows a VM to boot via PXE.
     */
    installationMethod?: pulumi.Input<string>;
    ipv4Addresses?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * This is only accessible if guest-tools is installed in the VM. While the output contains a list of ipv6 addresses, the presence of an IP address is only guaranteed if `expectedIpCidr` is set for that interface. The list contains the ipv6 addresses across all network interfaces in order.
     */
    ipv6Addresses?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The amount of memory in bytes the VM will have.\n\n!!! WARNING: Updates to this field will cause the VM to stop and start, as it sets both dynamic and static maximums.
     */
    memoryMax?: pulumi.Input<number>;
    /**
     * The amount of memory in bytes the VM will have. Set this value equal to memoryMax to have a static memory.
     */
    memoryMin?: pulumi.Input<number>;
    /**
     * The description of the VM.
     */
    nameDescription?: pulumi.Input<string>;
    /**
     * The name of the VM.
     */
    nameLabel?: pulumi.Input<string>;
    /**
     * The network for the VM.
     */
    networks?: pulumi.Input<pulumi.Input<inputs.VmNetwork>[]>;
    /**
     * The power state of the VM. This can be Running, Halted, Paused or Suspended.
     */
    powerState?: pulumi.Input<string>;
    resourceSet?: pulumi.Input<string>;
    /**
     * Enable UEFI secure boot for the VM.
     */
    secureBoot?: pulumi.Input<boolean>;
    /**
     * Number of seconds the VM should be delayed from starting.
     */
    startDelay?: pulumi.Input<number>;
    /**
     * The tags (labels) applied to the given entity. Not used for filtering if empty.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ID of the VM template to create the new VM from.
     */
    template?: pulumi.Input<string>;
    /**
     * The video adapter the VM should use. Possible values include std and cirrus.
     */
    vga?: pulumi.Input<string>;
    /**
     * The videoram option the VM should use. Possible values include 1, 2, 4, 8, 16
     */
    videoram?: pulumi.Input<number>;
    /**
     * The key value pairs to be populated in xenstore.
     */
    xenstore?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a Vm resource.
 */
export interface VmArgs {
    /**
     * The preferred host you would like the VM to run on. If changed on an existing VM it will require a reboot for the VM to be rescheduled.
     */
    affinityHost?: pulumi.Input<string>;
    /**
     * If the VM will automatically turn on. Defaults to `false`.
     */
    autoPoweron?: pulumi.Input<boolean>;
    /**
     * List of operations on a VM that are not permitted. Examples include: clean_reboot, clean_shutdown, hard_reboot, hard_shutdown, pause, shutdown, suspend, destroy. See: https://xapi-project.github.io/xen-api/classes/vm.html#enum_vm_operations
     */
    blockedOperations?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ISO that should be attached to VM. This allows you to create a VM from a diskless template (any templates available from `xe template-list`) and install the OS from the following ISO.
     */
    cdrom?: pulumi.Input<inputs.VmCdrom>;
    /**
     * The type of clone to perform for the VM. Possible values include `fast` or `full` and defaults to `fast`. In order to perform a `full` clone, the VM template must not be a disk template.
     */
    cloneType?: pulumi.Input<string>;
    /**
     * The content of the cloud-init config to use. See the cloud init docs for more [information](https://cloudinit.readthedocs.io/en/latest/topics/examples.html).
     */
    cloudConfig?: pulumi.Input<string>;
    /**
     * The content of the cloud-init network configuration for the VM (uses [version 1](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html))
     */
    cloudNetworkConfig?: pulumi.Input<string>;
    coreOs?: pulumi.Input<boolean>;
    cpuCap?: pulumi.Input<number>;
    cpuWeight?: pulumi.Input<number>;
    /**
     * The number of CPUs the VM will have. Updates to this field will cause a stop and start of the VM if the new CPU value is greater than the max CPU value. This can be determined with the following command:
     * ```
     *
     * $ xo-cli xo.getAllObjects filter='json:{"id": "cf7b5d7d-3cd5-6b7c-5025-5c935c8cd0b8"}' | jq '.[].CPUs'
     * {
     *   "max": 4,
     *   "number": 2
     * }
     *
     * # Updating the VM to use 3 CPUs would happen without stopping/starting the VM
     * # Updating the VM to use 5 CPUs would stop/start the VM
     * ```
     */
    cpus: pulumi.Input<number>;
    /**
     * Determines whether the cloud config VDI should be deleted once the VM has booted. Defaults to `false`. If set to `true`, powerState must be set to `Running`.
     */
    destroyCloudConfigVdiAfterBoot?: pulumi.Input<boolean>;
    /**
     * The disk the VM will have access to.
     */
    disks: pulumi.Input<pulumi.Input<inputs.VmDisk>[]>;
    /**
     * Boolean parameter that allows a VM to use nested virtualization.
     */
    expNestedHvm?: pulumi.Input<boolean>;
    /**
     * The restart priority for the VM. Possible values are `best-effort`, `restart` and empty string (no restarts on failure. Defaults to empty string
     */
    highAvailability?: pulumi.Input<string>;
    host?: pulumi.Input<string>;
    /**
     * The firmware to use for the VM. Possible values are `bios` and `uefi`.
     */
    hvmBootFirmware?: pulumi.Input<string>;
    /**
     * This cannot be used with `cdrom`. Possible values are `network` which allows a VM to boot via PXE.
     */
    installationMethod?: pulumi.Input<string>;
    /**
     * The amount of memory in bytes the VM will have.\n\n!!! WARNING: Updates to this field will cause the VM to stop and start, as it sets both dynamic and static maximums.
     */
    memoryMax: pulumi.Input<number>;
    /**
     * The amount of memory in bytes the VM will have. Set this value equal to memoryMax to have a static memory.
     */
    memoryMin?: pulumi.Input<number>;
    /**
     * The description of the VM.
     */
    nameDescription?: pulumi.Input<string>;
    /**
     * The name of the VM.
     */
    nameLabel: pulumi.Input<string>;
    /**
     * The network for the VM.
     */
    networks: pulumi.Input<pulumi.Input<inputs.VmNetwork>[]>;
    /**
     * The power state of the VM. This can be Running, Halted, Paused or Suspended.
     */
    powerState?: pulumi.Input<string>;
    resourceSet?: pulumi.Input<string>;
    /**
     * Enable UEFI secure boot for the VM.
     */
    secureBoot?: pulumi.Input<boolean>;
    /**
     * Number of seconds the VM should be delayed from starting.
     */
    startDelay?: pulumi.Input<number>;
    /**
     * The tags (labels) applied to the given entity. Not used for filtering if empty.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ID of the VM template to create the new VM from.
     */
    template: pulumi.Input<string>;
    /**
     * The video adapter the VM should use. Possible values include std and cirrus.
     */
    vga?: pulumi.Input<string>;
    /**
     * The videoram option the VM should use. Possible values include 1, 2, 4, 8, 16
     */
    videoram?: pulumi.Input<number>;
    /**
     * The key value pairs to be populated in xenstore.
     */
    xenstore?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
